server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /sanseong/alliwanttodo
spring:
  # postgres start ------------------------------------------------------------------------------------------------------
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
  datasource:
    url: ${DB_CONNECTION:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
  # postgres end --------------------------------------------------------------------------------------------------------

logging:
  level:
    com.htbeyond.mid.parking.vehicle: debug
